/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 a.glb --transform 
Files: a.glb [25.3KB] > /Users/rami/Desktop/interactive-piano/public/a-transformed.glb [4.71KB] (81%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/a-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-8.152, 0.56, -12.612]}>
        <mesh geometry={nodes.Cube1059.geometry} material={materials.white} />
        <mesh geometry={nodes.Cube1059_1.geometry} material={materials.black} />
      </group>
    </group>
  )
}

useGLTF.preload('/a-transformed.glb')
