/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 a_new.glb --transform 
Files: a_new.glb [25.24KB] > /Users/rami/Desktop/projects/remix-cloudflare-piano/public/a_new-transformed.glb [5.06KB] (80%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function A_new(props) {
  const { nodes, materials } = useGLTF('/a_new-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[12.634, 8.152, -1.683]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Cube1059.geometry} material={materials.white} />
        <mesh geometry={nodes.Cube1059_1.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/a_new-transformed.glb')
