/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 a_sharp_new.glb --transform 
Files: a_sharp_new.glb [26.49KB] > /Users/rami/Desktop/projects/remix-cloudflare-piano/public/a_sharp_new-transformed.glb [3.83KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function A_sharp_new(props) {
  const { nodes, materials } = useGLTF('/a_sharp_new-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Black004.geometry} material={materials.Material} position={[13.879, 8.094, 1.922]} rotation={[0, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/a_sharp_new-transformed.glb')
