/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 a_sharp.glb --transform 
Files: a_sharp.glb [25.99KB] > /Users/rami/Desktop/interactive-piano/public/a_sharp-transformed.glb [3.52KB] (86%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/a_sharp-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Black004.geometry} material={materials.black} position={[-8.094, -0.052, -13.879]} />
    </group>
  )
}

useGLTF.preload('/a_sharp-transformed.glb')
