/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 c.glb --transform 
Files: c.glb [63.15KB] > /Users/rami/Desktop/interactive-piano/public/c-transformed.glb [8.44KB] (87%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/c-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-8.152, 0.556, 0.57]}>
        <mesh geometry={nodes.Cube1051.geometry} material={materials.white} />
        <mesh geometry={nodes.Cube1051_1.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/c-transformed.glb')
