/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 c_sharp_new.glb --transform 
Files: c_sharp_new.glb [26.49KB] > /Users/rami/Desktop/projects/remix-cloudflare-piano/public/c_sharp_new-transformed.glb [3.82KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function C_sharp_new(props) {
  const { nodes, materials } = useGLTF('/c_sharp_new-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Black.geometry} material={materials.Material} position={[1.133, 8.094, 1.922]} rotation={[0, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/c_sharp_new-transformed.glb')
