/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 c_sharp.glb --transform 
Files: c_sharp.glb [26.05KB] > /Users/rami/Desktop/interactive-piano/public/c_sharp-transformed.glb [3.51KB] (87%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/c_sharp-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Black.geometry} material={materials.black} position={[-8.094, -0.052, -1.133]} />
    </group>
  )
}

useGLTF.preload('/c_sharp-transformed.glb')
