/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 d.glb --transform 
Files: d.glb [25.4KB] > /Users/rami/Desktop/interactive-piano/public/d-transformed.glb [4.68KB] (82%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/d-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-8.152, 0.556, -2.436]}>
        <mesh geometry={nodes.Cube1055.geometry} material={materials.white} />
        <mesh geometry={nodes.Cube1055_1.geometry} material={materials.black} />
      </group>
    </group>
  )
}

useGLTF.preload('/d-transformed.glb')
