/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 d_new.glb --transform 
Files: d_new.glb [24.72KB] > /Users/rami/Desktop/projects/remix-cloudflare-piano/public/d_new-transformed.glb [5.03KB] (80%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function D_new(props) {
  const { nodes, materials } = useGLTF('/d_new-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[2.434, 0, -1.683]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Cube1055.geometry} material={materials.white} />
        <mesh geometry={nodes.Cube1055_1.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/d_new-transformed.glb')
