/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 d_sharp_new.glb --transform 
Files: d_sharp_new.glb [26.43KB] > /Users/rami/Desktop/projects/remix-cloudflare-piano/public/d_sharp_new-transformed.glb [3.83KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function D_sharp_new(props) {
  const { nodes, materials } = useGLTF('/d_sharp_new-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Black001.geometry} material={materials.Material} position={[3.755, 8.094, 1.922]} rotation={[0, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/d_sharp_new-transformed.glb')
