/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 d_sharp.glb --transform 
Files: d_sharp.glb [25.98KB] > /Users/rami/Desktop/interactive-piano/public/d_sharp-transformed.glb [3.52KB] (86%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/d_sharp-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Black001.geometry} material={materials.black} position={[-8.094, -0.052, -3.755]} />
    </group>
  )
}

useGLTF.preload('/d_sharp-transformed.glb')
