/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 experimental_f.glb --transform 
Files: experimental_f.glb [26.98KB] > /Users/rami/Desktop/projects/remix-cloudflare-piano/public/experimental_f-transformed.glb [5.1KB] (81%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/experimental_f-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[7.534, 8.152, -1.683]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Cube1057.geometry} material={materials.white} />
        <mesh geometry={nodes.Cube1057_1.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/experimental_f-transformed.glb')
