/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 experimental_c.glb --transform 
Files: experimental_c.glb [63.33KB] > /Users/rami/Desktop/projects/remix-cloudflare-piano/public/experimental_c-transformed.glb [8.92KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/experimental_c-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.116, 8.147, -1.695]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Cube1051.geometry} material={materials.white} />
        <mesh geometry={nodes.Cube1051_1.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/experimental_c-transformed.glb')
