/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 experimental_f_sharp.glb --transform 
Files: experimental_f_sharp.glb [26.49KB] > /Users/rami/Desktop/projects/remix-cloudflare-piano/public/experimental_f_sharp-transformed.glb [3.83KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/experimental_f_sharp-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Black002.geometry} material={materials.Material} position={[8.816, 8.094, 1.922]} rotation={[0, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/experimental_f_sharp-transformed.glb')
