/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 experimental_e.glb --transform 
Files: experimental_e.glb [26.36KB] > /Users/rami/Desktop/projects/remix-cloudflare-piano/public/experimental_e-transformed.glb [5.21KB] (80%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/experimental_e-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[4.984, 8.152, -1.683]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Cube1056.geometry} material={materials.white} />
        <mesh geometry={nodes.Cube1056_1.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/experimental_e-transformed.glb')
