/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 experimental_b.glb --transform 
Files: experimental_b.glb [27.04KB] > /Users/rami/Desktop/projects/remix-cloudflare-piano/public/experimental_b-transformed.glb [5.19KB] (81%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/experimental_b-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[15.184, 8.152, -1.683]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Cube1060.geometry} material={materials.white} />
        <mesh geometry={nodes.Cube1060_1.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/experimental_b-transformed.glb')
