/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 experimental_g.glb --transform 
Files: experimental_g.glb [25.32KB] > /Users/rami/Desktop/projects/remix-cloudflare-piano/public/experimental_g-transformed.glb [5.12KB] (80%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/experimental_g-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[10.084, 8.15, -1.692]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Cube1058.geometry} material={materials.white} />
        <mesh geometry={nodes.Cube1058_1.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/experimental_g-transformed.glb')
