/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 f.glb --transform 
Files: f.glb [27.09KB] > /Users/rami/Desktop/interactive-piano/public/f-transformed.glb [4.72KB] (83%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/f-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-8.152, 0.556, -7.096]}>
        <mesh geometry={nodes.Cube1057.geometry} material={materials.white} />
        <mesh geometry={nodes.Cube1057_1.geometry} material={materials.black} />
      </group>
    </group>
  )
}

useGLTF.preload('/f-transformed.glb')
