/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 f_sharp_new.glb --transform 
Files: f_sharp_new.glb [26.49KB] > /Users/rami/Desktop/projects/remix-cloudflare-piano/public/f_sharp_new-transformed.glb [3.83KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function F_sharp_new(props) {
  const { nodes, materials } = useGLTF('/f_sharp_new-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Black002.geometry} material={materials.Material} position={[8.816, 0, 1.922]} rotation={[0, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/f_sharp_new-transformed.glb')
