/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 g.glb --transform 
Files: g.glb [25.29KB] > /Users/rami/Desktop/interactive-piano/public/g-transformed.glb [4.69KB] (81%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/g-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-8.147, 0.568, -10.08]}>
        <mesh geometry={nodes.Cube1058.geometry} material={materials.white} />
        <mesh geometry={nodes.Cube1058_1.geometry} material={materials.black} />
      </group>
    </group>
  )
}

useGLTF.preload('/g-transformed.glb')
