/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 g_new.glb --transform 
Files: g_new.glb [25.32KB] > /Users/rami/Desktop/projects/remix-cloudflare-piano/public/g_new-transformed.glb [5.12KB] (80%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function G_new(props) {
  const { nodes, materials } = useGLTF('/g_new-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[10.084, 8.15, -1.692]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Cube1058.geometry} material={materials.white} />
        <mesh geometry={nodes.Cube1058_1.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/g_new-transformed.glb')
