/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 g_sharp_new.glb --transform 
Files: g_sharp_new.glb [26.49KB] > /Users/rami/Desktop/projects/remix-cloudflare-piano/public/g_sharp_new-transformed.glb [3.83KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function G_sharp_new(props) {
  const { nodes, materials } = useGLTF('/g_sharp_new-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Black003.geometry} material={materials.Material} position={[11.345, 0, 1.922]} rotation={[0, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/g_sharp_new-transformed.glb')
