// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.16 b.glb --transform 
// Files: b.glb [26.91KB] > /Users/rami/Desktop/interactive-piano/public/b-transformed.glb [4.84KB] (82%)
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Model(props) {
//   const { nodes, materials } = useGLTF('/b-transformed.glb')
//   return (
//     <group {...props} dispose={null}>
//       <group position={[-8.152, 0.56, -15.184]}>
//         <mesh geometry={nodes.Cube1060.geometry} material={materials.white} />
//         <mesh geometry={nodes.Cube1060_1.geometry} material={materials.black} />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/b-transformed.glb')
