// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 b_new.glb --transform 
// Files: b_new.glb [27.04KB] > /Users/rami/Desktop/projects/remix-cloudflare-piano/public/b_new-transformed.glb [5.19KB] (81%)
// */

// import React from 'react'
// import { useGLTF } from '@react-three/drei'

// export function B_new(props) {
//   const { nodes, materials } = useGLTF('/b_new-transformed.glb')
//   return (
//     <group {...props} dispose={null}>
//       <group position={[15.184, 0, -1.683]} rotation={[0, 0, -Math.PI / 2]}>
//         <mesh geometry={nodes.Cube1060.geometry} material={materials.white} />
//         <mesh geometry={nodes.Cube1060_1.geometry} material={materials.Material} />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/b_new-transformed.glb')
