// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 c_new.glb --transform 
// Files: c_new.glb [63.33KB] > /Users/rami/Desktop/projects/remix-cloudflare-piano/public/c_new-transformed.glb [8.92KB] (86%)
// */
// // import React from 'react'
// import useStore from '../app/store/keyPressStore'
// import { useGLTF } from '@react-three/drei'
// import * as THREE from 'three'

// const redMaterial = new THREE.MeshStandardMaterial({
//   color: 'red',
//   roughness: 0.5,
//   metalness: 0.2,
//   emissive: '#ff3333',
//   emissiveIntensity: 0.2
// })

// export function C_new(props) {
//   const { nodes, materials } = useGLTF('/c_new-transformed.glb')
//   // Subscribe to keystore to track key press state
//   const { noteNumber } = props;
//   console.log("noteNumber: ", noteNumber)
//   console.log("re-rendering")
//   const isPressed = useStore(state => state[noteNumber])

//   // Bypass react rendering
//   // useEffect(() => {
//   //   if (materials[color]) {
//   //     clonedMaterialRef.copy(materials[color]);
//   //     if (pressed) {
//   //       if(meshRef.current) {
//   //         meshRef.current.material  = standardMaterial
//   //       }  
//   //     } else {
//   //       meshRef.current.material = clonedMaterialRef
//   //     }
//   //   }
//   // }, [pressed]);

//   return (
//     <group {...props} dispose={null}>
//       <group position={[-0.116, 0, -1.695]} rotation={[0, 0, -Math.PI / 2]}>
//         <mesh geometry={nodes.Cube1051.geometry} material={isPressed ? redMaterial : materials.white} />
//         {/* <mesh geometry={nodes.Cube1051_1.geometry} material={materials.Material} /> */}
//       </group>
//     </group>
//   )
// }

// useGLTF.preload(['/c_new-transformed.glb'])
