/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 e.glb --transform 
Files: e.glb [26.91KB] > /Users/rami/Desktop/interactive-piano/public/e-transformed.glb [4.84KB] (82%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/e-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-8.147, 0.568, -5.022]}>
        <mesh geometry={nodes.Cube1056.geometry} material={materials.white} />
        <mesh geometry={nodes.Cube1056_1.geometry} material={materials.black} />
      </group>
    </group>
  )
}

useGLTF.preload('/e-transformed.glb')
