/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 g_sharp.glb --transform 
Files: g_sharp.glb [25.99KB] > /Users/rami/Desktop/interactive-piano/public/g_sharp-transformed.glb [3.52KB] (86%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/g_sharp-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Black003.geometry} material={materials.black} position={[-8.094, -0.052, -11.345]} />
    </group>
  )
}

useGLTF.preload('/g_sharp-transformed.glb')
