/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rotated_a.glb --transform 
Files: rotated_a.glb [0.13KB] > /Users/rami/Desktop/projects/remix-cloudflare-piano/public/rotated_a-transformed.glb [0.13KB] (0%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rotated_a-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group />
    </group>
  )
}

useGLTF.preload('/rotated_a-transformed.glb')
